# 特征工程

In [1]:
import pandas as pd
import json
from collections import OrderedDict
from sklearn import preprocessing

## 读取数据

In [2]:
train_data = pd.read_csv('../data/movielens/train.csv')
test_data = pd.read_csv('../data/movielens/test.csv')

In [3]:
train_data

,movieId,userId,rating,timestamp,label,releaseYear,movieGenre1,movieGenre2,movieGenre3,movieRatingCount,...,userRatingCount,userAvgReleaseYear,userReleaseYearStddev,userAvgRating,userRatingStddev,userGenre1,userGenre2,userGenre3,userGenre4,userGenre5
0,1,15555,3.0,900953740,0,1995,Adventure,Animation,Children,10759,...,92,1992,8.98,3.86,0.74,Drama,Comedy,Thriller,Action,Crime
1,1,25912,3.5,1111631768,1,1995,Adventure,Animation,Children,10759,...,21,1988,14.09,3.48,1.28,Action,Comedy,Romance,Adventure,Thriller
2,1,29912,3.0,866820360,0,1995,Adventure,Animation,Children,10759,...,4,1995,0.50,3.00,0.00,NaN,NaN,NaN,NaN,NaN
3,10,17686,0.5,1195555011,0,1995,Action,Adventure,Thriller,6330,...,35,1992,8.35,2.97,1.48,Comedy,Drama,Adventure,Action,Thriller
4,104,20158,4.0,1155357691,1,1996,Comedy,NaN,NaN,3954,...,81,1991,8.70,3.60,0.72,Thriller,Drama,Action,Crime,Adventure
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88822,968,26865,3.0,854092232,0,1968,Horror,Sci-Fi,Thriller,1824,...,94,1991,12.23,3.35,0.85,Drama,Thriller,Comedy,Crime,Romance
88823,968,8507,2.0,974709061,0,1968,Horror,Sci-Fi,Thriller,1824,...,5,1994,0.89,2.00,1.00,NaN,NaN,NaN,NaN,NaN
88824,969,16689,5.0,857854044,1,1951,Adventure,Comedy,Romance,2380,...,97,1992,9.95,3.53,0.82,Drama,Comedy,Crime,Romance,Thriller
88825,969,26460,2.0,1250279576,0,1951,Adventure,Comedy,Romance,2380,...,55,1990,11.78,2.73,1.42,Thriller,Crime,Drama,Comedy,Sci-Fi
88826,970,3033,2.0,1272394603,0,1953,Adventure,Comedy,Crime,98,...,100,1985,17.64,3.67,0.89,Drama,Romance,Comedy,Thriller,Crime

In [4]:
test_data

,movieId,userId,rating,timestamp,label,releaseYear,movieGenre1,movieGenre2,movieGenre3,movieRatingCount,...,userRatingCount,userAvgReleaseYear,userReleaseYearStddev,userAvgRating,userRatingStddev,userGenre1,userGenre2,userGenre3,userGenre4,userGenre5
0,1,14887,3.0,830155608,0,1995,Adventure,Animation,Children,10759,...,6,1992,2.64,3.67,0.52,Drama,Action,Thriller,Adventure,Crime
1,10,11888,1.0,845674484,0,1995,Action,Adventure,Thriller,6330,...,22,1993,1.70,3.36,1.14,Comedy,Thriller,Adventure,Crime,Action
2,10,27990,4.0,1197772963,1,1995,Action,Adventure,Thriller,6330,...,46,1989,12.99,3.37,1.00,Drama,Adventure,Crime,Thriller,Comedy
3,135,27108,5.0,865275107,1,1996,Comedy,NaN,NaN,1390,...,25,1994,3.76,3.52,1.33,Action,Thriller,Adventure,Sci-Fi,Romance
4,15,23843,4.0,839634055,1,1995,Action,Adventure,Romance,634,...,100,1993,5.75,3.58,0.68,Drama,Thriller,Romance,Comedy,Action
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22435,924,29743,4.5,1113684873,1,1968,Adventure,Drama,Sci-Fi,5530,...,47,1983,18.74,3.85,0.62,Drama,Comedy,Thriller,Adventure,Action
22436,934,20817,4.0,858587157,1,1950,Comedy,NaN,NaN,857,...,100,1989,13.10,3.94,0.86,Drama,Thriller,Comedy,Romance,Action
22437,949,21305,3.0,949289910,0,1955,Drama,NaN,NaN,471,...,22,1960,22.55,4.50,0.60,Thriller,Romance,Drama,Comedy,Mystery
22438,969,3033,3.5,1253391526,1,1951,Adventure,Comedy,Romance,2380,...,99,1985,17.39,3.67,0.90,Drama,Romance,Comedy,Thriller,Crime
22439,996,18466,5.0,845284101,1,1996,Action,Crime,Drama,697,...,100,1994,1.83,3.28,1.01,Comedy,Action,Thriller,Romance,Crime

In [5]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88827 entries, 0 to 88826
Data columns (total 27 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   movieId                88827 non-null  int64
 1   userId                 88827 non-null  int64
 2   rating                 88827 non-null  float64
 3   timestamp              88827 non-null  int64
 4   label                  88827 non-null  int64
 5   releaseYear            88827 non-null  int64
 6   movieGenre1            88827 non-null  object
 7   movieGenre2            75109 non-null  object
 8   movieGenre3            48071 non-null  object
 9   movieRatingCount       88827 non-null  int64
 10  movieAvgRating         88827 non-null  float64
 11  movieRatingStddev      88827 non-null  float64
 12  userRatedMovie1        87600 non-null  float64
 13  userRatedMovie2        84810 non-null  float64
 14  userRatedMovie3        81027 non-null  float64
 15  userRatedMovie4        77590 non-null  float64
 16  userRatedMovie5        74372 non-null  float64
 17  userRatingCount        88827 non-null  int64
 18  userAvgReleaseYear     88827 non-null  int64
 19  userReleaseYearStddev  88827 non-null  float64
 20  userAvgRating          88827 non-null  float64
 21  userRatingStddev       88827 non-null  float64
 22  userGenre1             87600 non-null  object
 23  userGenre2             87218 non-null  object
 24  userGenre3             86245 non-null  object
 25  userGenre4             84755 non-null  object
 26  userGenre5             82524 non-null  object
dtypes: float64(11), int64(8), object(8)
memory usage: 18.3+ MB

In [6]:
test_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22440 entries, 0 to 22439
Data columns (total 27 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   movieId                22440 non-null  int64
 1   userId                 22440 non-null  int64
 2   rating                 22440 non-null  float64
 3   timestamp              22440 non-null  int64
 4   label                  22440 non-null  int64
 5   releaseYear            22440 non-null  int64
 6   movieGenre1            22440 non-null  object
 7   movieGenre2            18906 non-null  object
 8   movieGenre3            12099 non-null  object
 9   movieRatingCount       22440 non-null  int64
 10  movieAvgRating         22440 non-null  float64
 11  movieRatingStddev      22440 non-null  float64
 12  userRatedMovie1        22151 non-null  float64
 13  userRatedMovie2        21452 non-null  float64
 14  userRatedMovie3        20492 non-null  float64
 15  userRatedMovie4        19604 non-null  float64
 16  userRatedMovie5        18753 non-null  float64
 17  userRatingCount        22440 non-null  int64
 18  userAvgReleaseYear     22440 non-null  int64
 19  userReleaseYearStddev  22440 non-null  float64
 20  userAvgRating          22440 non-null  float64
 21  userRatingStddev       22440 non-null  float64
 22  userGenre1             22151 non-null  object
 23  userGenre2             22062 non-null  object
 24  userGenre3             21842 non-null  object
 25  userGenre4             21457 non-null  object
 26  userGenre5             20918 non-null  object
dtypes: float64(11), int64(8), object(8)
memory usage: 4.6+ MB

In [7]:
label = train_data.pop('label')
train_data.insert(loc=train_data.shape[1], column='label', value=label, allow_duplicates=False)

In [8]:
label = test_data.pop('label')
test_data.insert(loc=test_data.shape[1], column='label', value=label, allow_duplicates=False)

In [9]:
train_data

,movieId,userId,rating,timestamp,releaseYear,movieGenre1,movieGenre2,movieGenre3,movieRatingCount,movieAvgRating,...,userAvgReleaseYear,userReleaseYearStddev,userAvgRating,userRatingStddev,userGenre1,userGenre2,userGenre3,userGenre4,userGenre5,label
0,1,15555,3.0,900953740,1995,Adventure,Animation,Children,10759,3.91,...,1992,8.98,3.86,0.74,Drama,Comedy,Thriller,Action,Crime,0
1,1,25912,3.5,1111631768,1995,Adventure,Animation,Children,10759,3.91,...,1988,14.09,3.48,1.28,Action,Comedy,Romance,Adventure,Thriller,1
2,1,29912,3.0,866820360,1995,Adventure,Animation,Children,10759,3.91,...,1995,0.50,3.00,0.00,NaN,NaN,NaN,NaN,NaN,0
3,10,17686,0.5,1195555011,1995,Action,Adventure,Thriller,6330,3.42,...,1992,8.35,2.97,1.48,Comedy,Drama,Adventure,Action,Thriller,0
4,104,20158,4.0,1155357691,1996,Comedy,NaN,NaN,3954,3.40,...,1991,8.70,3.60,0.72,Thriller,Drama,Action,Crime,Adventure,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88822,968,26865,3.0,854092232,1968,Horror,Sci-Fi,Thriller,1824,3.64,...,1991,12.23,3.35,0.85,Drama,Thriller,Comedy,Crime,Romance,0
88823,968,8507,2.0,974709061,1968,Horror,Sci-Fi,Thriller,1824,3.64,...,1994,0.89,2.00,1.00,NaN,NaN,NaN,NaN,NaN,0
88824,969,16689,5.0,857854044,1951,Adventure,Comedy,Romance,2380,4.11,...,1992,9.95,3.53,0.82,Drama,Comedy,Crime,Romance,Thriller,1
88825,969,26460,2.0,1250279576,1951,Adventure,Comedy,Romance,2380,4.11,...,1990,11.78,2.73,1.42,Thriller,Crime,Drama,Comedy,Sci-Fi,0
88826,970,3033,2.0,1272394603,1953,Adventure,Comedy,Crime,98,3.51,...,1985,17.64,3.67,0.89,Drama,Romance,Comedy,Thriller,Crime,0

In [10]:
test_data

,movieId,userId,rating,timestamp,releaseYear,movieGenre1,movieGenre2,movieGenre3,movieRatingCount,movieAvgRating,...,userAvgReleaseYear,userReleaseYearStddev,userAvgRating,userRatingStddev,userGenre1,userGenre2,userGenre3,userGenre4,userGenre5,label
0,1,14887,3.0,830155608,1995,Adventure,Animation,Children,10759,3.91,...,1992,2.64,3.67,0.52,Drama,Action,Thriller,Adventure,Crime,0
1,10,11888,1.0,845674484,1995,Action,Adventure,Thriller,6330,3.42,...,1993,1.70,3.36,1.14,Comedy,Thriller,Adventure,Crime,Action,0
2,10,27990,4.0,1197772963,1995,Action,Adventure,Thriller,6330,3.42,...,1989,12.99,3.37,1.00,Drama,Adventure,Crime,Thriller,Comedy,1
3,135,27108,5.0,865275107,1996,Comedy,NaN,NaN,1390,3.00,...,1994,3.76,3.52,1.33,Action,Thriller,Adventure,Sci-Fi,Romance,1
4,15,23843,4.0,839634055,1995,Action,Adventure,Romance,634,2.71,...,1993,5.75,3.58,0.68,Drama,Thriller,Romance,Comedy,Action,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22435,924,29743,4.5,1113684873,1968,Adventure,Drama,Sci-Fi,5530,3.95,...,1983,18.74,3.85,0.62,Drama,Comedy,Thriller,Adventure,Action,1
22436,934,20817,4.0,858587157,1950,Comedy,NaN,NaN,857,3.52,...,1989,13.10,3.94,0.86,Drama,Thriller,Comedy,Romance,Action,1
22437,949,21305,3.0,949289910,1955,Drama,NaN,NaN,471,3.92,...,1960,22.55,4.50,0.60,Thriller,Romance,Drama,Comedy,Mystery,0
22438,969,3033,3.5,1253391526,1951,Adventure,Comedy,Romance,2380,4.11,...,1985,17.39,3.67,0.90,Drama,Romance,Comedy,Thriller,Crime,1
22439,996,18466,5.0,845284101,1996,Action,Crime,Drama,697,3.01,...,1994,1.83,3.28,1.01,Comedy,Action,Thriller,Romance,Crime,1

In [11]:
train_data['label'].value_counts()

1    50012
0    38815
Name: label, dtype: int64

In [12]:
test_data['label'].value_counts()

1    12584
0     9856
Name: label, dtype: int64

In [13]:
column_names = list(train_data.columns.values)
column_names.remove('label')
column_names

['movieId',
 'userId',
 'rating',
 'timestamp',
 'releaseYear',
 'movieGenre1',
 'movieGenre2',
 'movieGenre3',
 'movieRatingCount',
 'movieAvgRating',
 'movieRatingStddev',
 'userRatedMovie1',
 'userRatedMovie2',
 'userRatedMovie3',
 'userRatedMovie4',
 'userRatedMovie5',
 'userRatingCount',
 'userAvgReleaseYear',
 'userReleaseYearStddev',
 'userAvgRating',
 'userRatingStddev',
 'userGenre1',
 'userGenre2',
 'userGenre3',
 'userGenre4',
 'userGenre5']

In [14]:
# 数值型特征
numerical_columns = ['rating', 'timestamp', 'releaseYear', 'movieRatingCount', 'movieAvgRating',
                     'movieRatingStddev', 'userRatingCount', 'userAvgReleaseYear',
                     'userReleaseYearStddev', 'userAvgRating', 'userRatingStddev']
# 类别型特征
categorical_columns = ['movieId', 'userId', 'movieGenre1', 'movieGenre2', 'movieGenre3', 'userRatedMovie1', 
                       'userRatedMovie2', 'userRatedMovie3', 'userRatedMovie4', 'userRatedMovie5', 'userGenre1', 
                       'userGenre2', 'userGenre3', 'userGenre4', 'userGenre5']
# 用户特征
user_columns = ['userId', 'rating', 'timestamp', 'userRatedMovie1', 'userRatedMovie2', 'userRatedMovie3',
                'userRatedMovie4', 'userRatedMovie5', 'userRatingCount', 'userAvgReleaseYear',
                'userReleaseYearStddev', 'userAvgRating', 'userRatingStddev',
                'userGenre1', 'userGenre2', 'userGenre3', 'userGenre4', 'userGenre5']
# 物品特征
item_columns = ['movieId', 'releaseYear', 'movieGenre1', 'movieGenre2', 'movieGenre3',
                'movieRatingCount', 'movieAvgRating', 'movieRatingStddev']

# 风格特征
genre_columns = ['movieGenre1', 'movieGenre2', 'movieGenre3',
                 'userGenre1', 'userGenre2', 'userGenre3', 'userGenre4', 'userGenre5']

# 好评电影ID特征
rated_columns = ['userRatedMovie1', 'userRatedMovie2',
                  'userRatedMovie3', 'userRatedMovie4', 'userRatedMovie5']

In [15]:
# genre features vocabulary 电影类型特征
genre_vocab = [
    'Film-Noir', 'Action', 'Adventure', 'Horror', 'Romance', 'War', 'Comedy',
    'Western', 'Documentary', 'Sci-Fi', 'Drama', 'Thriller', 'Crime',
    'Fantasy', 'Animation', 'IMAX', 'Mystery', 'Children', 'Musical'
]

## 缺失值填充

In [16]:
train_data.isnull().sum() / len(train_data)

movieId                  0.000000
userId                   0.000000
rating                   0.000000
timestamp                0.000000
releaseYear              0.000000
movieGenre1              0.000000
movieGenre2              0.154435
movieGenre3              0.458824
movieRatingCount         0.000000
movieAvgRating           0.000000
movieRatingStddev        0.000000
userRatedMovie1          0.013813
userRatedMovie2          0.045223
userRatedMovie3          0.087811
userRatedMovie4          0.126504
userRatedMovie5          0.162732
userRatingCount          0.000000
userAvgReleaseYear       0.000000
userReleaseYearStddev    0.000000
userAvgRating            0.000000
userRatingStddev         0.000000
userGenre1               0.013813
userGenre2               0.018114
userGenre3               0.029068
userGenre4               0.045842
userGenre5               0.070958
label                    0.000000
dtype: float64

In [17]:
test_data.isnull().sum() / len(test_data)

movieId                  0.000000
userId                   0.000000
rating                   0.000000
timestamp                0.000000
releaseYear              0.000000
movieGenre1              0.000000
movieGenre2              0.157487
movieGenre3              0.460829
movieRatingCount         0.000000
movieAvgRating           0.000000
movieRatingStddev        0.000000
userRatedMovie1          0.012879
userRatedMovie2          0.044029
userRatedMovie3          0.086809
userRatedMovie4          0.126381
userRatedMovie5          0.164305
userRatingCount          0.000000
userAvgReleaseYear       0.000000
userReleaseYearStddev    0.000000
userAvgRating            0.000000
userRatingStddev         0.000000
userGenre1               0.012879
userGenre2               0.016845
userGenre3               0.026649
userGenre4               0.043806
userGenre5               0.067825
label                    0.000000
dtype: float64

In [18]:
for feature in genre_columns:
    train_data[feature].fillna(train_data[feature].mode()[0], inplace=True)
    test_data[feature].fillna(test_data[feature].mode()[0], inplace=True)

In [19]:
for feature in rated_columns:
    train_data[feature].fillna(train_data[feature].mean(), inplace=True)
    test_data[feature].fillna(test_data[feature].mean(), inplace=True)

## 排序

In [20]:
train_data.sort_values('timestamp', inplace=True)
test_data.sort_values('timestamp', inplace=True)

In [21]:
train_data

,movieId,userId,rating,timestamp,releaseYear,movieGenre1,movieGenre2,movieGenre3,movieRatingCount,movieAvgRating,...,userAvgReleaseYear,userReleaseYearStddev,userAvgRating,userRatingStddev,userGenre1,userGenre2,userGenre3,userGenre4,userGenre5,label
56273,95,8050,3.0,824133948,1996,Action,Adventure,Thriller,4791,3.10,...,1995,0.25,3.62,1.09,Thriller,Mystery,Crime,Drama,Children,0
55922,110,8050,4.0,824559456,1995,Action,Drama,War,11637,4.04,...,1995,0.32,3.61,1.04,Thriller,Crime,Drama,Mystery,Children,1
36508,1,22528,4.0,825006653,1995,Adventure,Animation,Children,10759,3.91,...,1995,0.00,3.75,1.50,Action,Thriller,Crime,Children,Drama,1
36520,104,22528,2.0,825006881,1996,Comedy,Drama,Thriller,3954,3.40,...,1994,4.54,3.83,1.29,Drama,Thriller,Adventure,Action,Crime,0
36799,5,22528,4.0,825006881,1995,Comedy,Drama,Thriller,2629,3.06,...,1994,4.67,3.82,1.33,Drama,Thriller,Adventure,Action,Crime,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70495,47,15844,4.0,1427655597,1995,Mystery,Thriller,Thriller,9335,4.06,...,1991,8.13,3.14,1.13,Comedy,Thriller,Action,Horror,Crime,1
47802,32,27135,5.0,1427672290,1995,Mystery,Sci-Fi,Thriller,9694,3.89,...,1991,6.95,3.64,0.74,Drama,Crime,Thriller,Mystery,Comedy,1
2985,380,11966,2.0,1427739805,1994,Action,Adventure,Comedy,9364,3.48,...,1987,15.32,4.00,1.03,Drama,Thriller,Crime,Action,Sci-Fi,0
2951,344,11966,2.5,1427739810,1994,Comedy,Drama,Thriller,8273,2.98,...,1987,14.82,3.82,1.20,Drama,Thriller,Crime,Action,Sci-Fi,0
2974,364,11966,2.0,1427739815,1994,Adventure,Animation,Children,8464,3.78,...,1987,14.60,3.78,1.20,Drama,Thriller,Crime,Action,Sci-Fi,0

In [22]:
test_data

,movieId,userId,rating,timestamp,releaseYear,movieGenre1,movieGenre2,movieGenre3,movieRatingCount,movieAvgRating,...,userAvgReleaseYear,userReleaseYearStddev,userAvgRating,userRatingStddev,userGenre1,userGenre2,userGenre3,userGenre4,userGenre5,label
9263,45,22528,3.0,825007097,1995,Comedy,Drama,Thriller,1910,3.39,...,1994,4.31,3.80,1.32,Thriller,Drama,Adventure,Crime,Action,0
18584,338,11825,4.0,826816195,1995,Action,Sci-Fi,Thriller,984,2.99,...,1994,0.71,4.29,0.62,Drama,Thriller,Action,Crime,Comedy,1
8524,216,1540,4.0,827310247,1995,Comedy,Drama,Thriller,1867,3.22,...,1995,0.46,4.00,1.00,Action,Adventure,Drama,Comedy,Thriller,1
5640,317,28062,4.0,827497762,1994,Comedy,Drama,Fantasy,3486,3.14,...,1994,0.41,4.83,0.41,Thriller,Crime,Drama,Comedy,Sci-Fi,1
5635,253,28062,4.0,827497762,1994,Drama,Horror,Thriller,6010,3.50,...,1994,0.51,4.07,1.14,Drama,Comedy,Thriller,Crime,Romance,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15659,912,21487,3.0,1427227515,1942,Drama,Romance,Thriller,5256,4.27,...,1984,13.00,3.79,0.95,Comedy,Crime,Drama,Action,Sci-Fi,0
13873,70,11406,4.0,1427449131,1996,Action,Comedy,Horror,2831,3.24,...,1990,8.06,4.45,0.39,Thriller,Drama,Action,Sci-Fi,Crime,1
8124,940,29707,5.0,1427486206,1938,Action,Adventure,Romance,841,3.88,...,1966,21.94,4.03,0.60,Romance,Drama,Comedy,Thriller,Adventure,1
8105,720,29707,4.0,1427491038,1996,Adventure,Animation,Comedy,1803,4.05,...,1977,22.61,3.99,0.48,Romance,Drama,Comedy,Thriller,Adventure,1
4411,926,3797,4.0,1427540767,1950,Drama,Drama,Thriller,1076,4.21,...,1985,16.81,2.92,1.05,Drama,Comedy,Thriller,Romance,Mystery,1

## 归一化

In [23]:
numerical_df = train_data[numerical_columns]
numerical_df = (numerical_df - numerical_df.min()) / (numerical_df.max() - numerical_df.min())
train_data[numerical_columns] = numerical_df

In [24]:
numerical_df = test_data[numerical_columns]
numerical_df = (numerical_df - numerical_df.min()) / (numerical_df.max() - numerical_df.min())
test_data[numerical_columns] = numerical_df

In [25]:
train_data

,movieId,userId,rating,timestamp,releaseYear,movieGenre1,movieGenre2,movieGenre3,movieRatingCount,movieAvgRating,...,userAvgReleaseYear,userReleaseYearStddev,userAvgRating,userRatingStddev,userGenre1,userGenre2,userGenre3,userGenre4,userGenre5,label
56273,95,8050,0.555556,0.000000,0.972222,Action,Adventure,Thriller,0.327699,0.567308,...,0.983333,0.005796,0.693333,0.342767,Thriller,Mystery,Crime,Drama,Children,0
55922,110,8050,0.777778,0.000705,0.958333,Action,Drama,War,0.796154,0.868590,...,0.983333,0.007419,0.691111,0.327044,Thriller,Crime,Drama,Mystery,Children,1
36508,1,22528,0.777778,0.001446,0.958333,Adventure,Animation,Children,0.736075,0.826923,...,0.983333,0.000000,0.722222,0.471698,Action,Thriller,Crime,Children,Drama,1
36520,104,22528,0.333333,0.001446,0.972222,Comedy,Drama,Thriller,0.270426,0.663462,...,0.966667,0.105263,0.740000,0.405660,Drama,Thriller,Adventure,Action,Crime,0
36799,5,22528,0.777778,0.001446,0.958333,Comedy,Drama,Thriller,0.179759,0.554487,...,0.966667,0.108277,0.737778,0.418239,Drama,Thriller,Adventure,Action,Crime,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70495,47,15844,0.777778,0.999860,0.958333,Mystery,Thriller,Thriller,0.638634,0.875000,...,0.916667,0.188500,0.586667,0.355346,Comedy,Thriller,Action,Horror,Crime,1
47802,32,27135,1.000000,0.999888,0.958333,Mystery,Sci-Fi,Thriller,0.663200,0.820513,...,0.916667,0.161141,0.697778,0.232704,Drama,Crime,Thriller,Mystery,Comedy,1
2985,380,11966,0.333333,1.000000,0.944444,Action,Adventure,Comedy,0.640619,0.689103,...,0.850000,0.355205,0.777778,0.323899,Drama,Thriller,Crime,Action,Sci-Fi,0
2951,344,11966,0.444444,1.000000,0.944444,Comedy,Drama,Thriller,0.565964,0.528846,...,0.850000,0.343612,0.737778,0.377358,Drama,Thriller,Crime,Action,Sci-Fi,0
2974,364,11966,0.333333,1.000000,0.944444,Adventure,Animation,Children,0.579034,0.785256,...,0.850000,0.338511,0.728889,0.377358,Drama,Thriller,Crime,Action,Sci-Fi,0

In [26]:
test_data

,movieId,userId,rating,timestamp,releaseYear,movieGenre1,movieGenre2,movieGenre3,movieRatingCount,movieAvgRating,...,userAvgReleaseYear,userReleaseYearStddev,userAvgRating,userRatingStddev,userGenre1,userGenre2,userGenre3,userGenre4,userGenre5,label
9263,45,22528,0.555556,0.000000,0.971831,Comedy,Drama,Thriller,0.130560,0.602996,...,0.964912,0.099930,0.733333,0.415094,Thriller,Drama,Adventure,Crime,Action,0
18584,338,11825,0.777778,0.003002,0.971831,Action,Sci-Fi,Thriller,0.067196,0.453184,...,0.964912,0.016462,0.842222,0.194969,Drama,Thriller,Action,Crime,Comedy,1
8524,216,1540,0.777778,0.003822,0.971831,Comedy,Drama,Thriller,0.127617,0.539326,...,0.982456,0.010665,0.777778,0.314465,Action,Adventure,Drama,Comedy,Thriller,1
5640,317,28062,0.777778,0.004134,0.957746,Comedy,Drama,Fantasy,0.238402,0.509363,...,0.964912,0.009506,0.962222,0.128931,Thriller,Crime,Drama,Comedy,Sci-Fi,1
5635,253,28062,0.777778,0.004134,0.957746,Drama,Horror,Thriller,0.411113,0.644195,...,0.964912,0.011825,0.793333,0.358491,Drama,Comedy,Thriller,Crime,Romance,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15659,912,21487,0.555556,0.999480,0.225352,Drama,Romance,Thriller,0.359518,0.932584,...,0.789474,0.301414,0.731111,0.298742,Comedy,Crime,Drama,Action,Sci-Fi,0
13873,70,11406,0.777778,0.999848,0.985915,Action,Comedy,Horror,0.193581,0.546816,...,0.894737,0.186877,0.877778,0.122642,Thriller,Drama,Action,Sci-Fi,Crime,1
8124,940,29707,1.000000,0.999909,0.169014,Action,Adventure,Romance,0.057411,0.786517,...,0.473684,0.508695,0.784444,0.188679,Romance,Drama,Comedy,Thriller,Adventure,1
8105,720,29707,0.777778,0.999917,0.985915,Adventure,Animation,Comedy,0.123238,0.850187,...,0.666667,0.524229,0.775556,0.150943,Romance,Drama,Comedy,Thriller,Adventure,1
4411,926,3797,0.777778,1.000000,0.338028,Drama,Drama,Thriller,0.073491,0.910112,...,0.807018,0.389752,0.537778,0.330189,Drama,Comedy,Thriller,Romance,Mystery,1

## 特征编码

In [27]:
for feature in categorical_columns:
    feature_mapping = {val:i for i,val in enumerate(set(pd.concat([train_data[feature], test_data[feature]])))}
    train_data[feature] = train_data[feature].map(feature_mapping)
    test_data[feature] = test_data[feature].map(feature_mapping)

In [28]:
train_data

,movieId,userId,rating,timestamp,releaseYear,movieGenre1,movieGenre2,movieGenre3,movieRatingCount,movieAvgRating,...,userAvgReleaseYear,userReleaseYearStddev,userAvgRating,userRatingStddev,userGenre1,userGenre2,userGenre3,userGenre4,userGenre5,label
56273,92,6055,0.555556,0.000000,0.972222,15,6,2,0.327699,0.567308,...,0.983333,0.005796,0.693333,0.342767,13,4,16,16,6,0
55922,106,6055,0.777778,0.000705,0.958333,15,10,1,0.796154,0.868590,...,0.983333,0.007419,0.691111,0.327044,13,16,17,4,6,1
36508,0,16938,0.777778,0.001446,0.958333,6,9,13,0.736075,0.826923,...,0.983333,0.000000,0.722222,0.471698,11,12,16,6,16,1
36520,101,16938,0.333333,0.001446,0.972222,2,10,2,0.270426,0.663462,...,0.966667,0.105263,0.740000,0.405660,16,12,14,11,17,0
36799,4,16938,0.777778,0.001446,0.958333,2,10,2,0.179759,0.554487,...,0.966667,0.108277,0.737778,0.418239,16,12,14,11,17,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70495,46,11939,0.777778,0.999860,0.958333,7,2,2,0.638634,0.875000,...,0.916667,0.188500,0.586667,0.355346,12,12,11,8,17,1
47802,31,20403,1.000000,0.999888,0.958333,7,1,2,0.663200,0.820513,...,0.916667,0.161141,0.697778,0.232704,16,16,12,4,13,1
2985,369,9005,0.333333,1.000000,0.944444,15,6,3,0.640619,0.689103,...,0.850000,0.355205,0.777778,0.323899,16,12,16,11,1,0
2951,333,9005,0.444444,1.000000,0.944444,2,10,2,0.565964,0.528846,...,0.850000,0.343612,0.737778,0.377358,16,12,16,11,1,0
2974,353,9005,0.333333,1.000000,0.944444,6,9,13,0.579034,0.785256,...,0.850000,0.338511,0.728889,0.377358,16,12,16,11,1,0

## 特征字典

生成数据集描述字典，格式如下

```json
# data/taobao_tiny_h5/feature_map.json
feature_map = {
    "dataset_id": "taobao_tiny_h5",
    "num_fields": 14,
    "num_features": 476,
    "input_length": 14,
    "feature_specs": {
        "userid": {
            "source": "",
            "type": "categorical",
            "vocab_size": 25,
            "index": 0
        },
        "adgroup_id": {
            "source": "",
            "type": "categorical",
            "vocab_size": 100,
            "index": 1
        },
        ...
    }
}
```

In [29]:
feature_map = OrderedDict()
feature_map['dataset_id'] = 'movielens'
feature_map['num_fields'] = len(column_names)

In [30]:
feature_map['feature_specs'] = OrderedDict()
for feature in column_names:
    feature_map['feature_specs'][feature] = {
        'source': 'user' if feature in user_columns else 'item',
        'type': 'numerical' if feature in numerical_columns else 'categorical',
        'vocab_size': 1 if feature in numerical_columns else pd.concat([train_data[feature], test_data[feature]]).nunique(),
        'index': train_data.columns.get_loc(feature)
    }

In [31]:
train_data.to_csv('../data/movielens/data_for_train.csv', index=False)
test_data.to_csv('../data/movielens/data_for_test.csv', index=False)
with open('../data/movielens/feature_map.json', 'w') as obj:
    json.dump(feature_map, obj)